### ISSUE TITLE
Limited characters, Kanji etc turns to questionmarks

### ISSUE THREAD

**Issue by Soitora** [jorinvo/googlesheets-sql-sync#10]
Hello, awesome program that I find very _very_ useful for my purpose. However, my table contains a fair bit of Japanese Kanji, Katakana and Hiragana and occasionally a off-character, this however turns to questionmarks during the conversion.

For example:
`セブンウップス; Sebunuppusu` becomes `???????; Sebunuppusu`

And:
`α/Alfa` becomes `?/Alfa`

I would be very grateful if there would be a fix for this, thank you so much and thanks again for the great program.

Sincerely, Soitora

**Comment by jorinvo** [comment]
Hi @Soitora! Glad to hear this is useful to you!
I assume you are using MySQL, not PostgreSQL, correct?
I could reproduce unicode problems in MySQL. PostgreSQL seems to do the right thing out of the box.
Now I specify a character set for the table and set the encoding for the DB connection.
Seems to work now for me.
Please try out the new release [0.6.1](https://github.com/jorinvo/googlesheets-sql-sync/releases/tag/0.6.1)

**Comment by Soitora** [comment]
Hey, yeah correct; MySQL.
It works like a charm from what I could test right now, so I'm going to close the issue!
Thanks for responding so fast with a fix! :)
