### ISSUE TITLE
Config file example

### ISSUE THREAD

**Issue by c0mpute123** [jorinvo/googlesheets-sql-sync#20]
While I'm usually pretty good with this stuff, connection to my sql fails.  Since there is no documents for the use of this, an example config file would go very far for instruction.  Thanks for all you do.

**Comment by jorinvo** [comment]
As [shown in the readme](https://github.com/jorinvo/googlesheets-sql-sync#usage), you can generate a template config file with:
`java -jar googlesheets-sql-sync.jar --init`

**Comment by c0mpute123** [comment]
Correct.  However, the contents of that file is where I'm having issue.  The connection will not authenticate with my sql server correctly.  Hence, an example with fake credentials would be great!  Your direction for the Google side was GREAT!  The sql side . . .

**Comment by jorinvo** [comment]
Th readme links to the JDBC driver docs where you can find a detailed explanation of the detailed options depending on your database (MySQL or PostgreSQL).

But maybe this example of a full config already helps you:

```json
{
  "sheets" : [ {
    "table" : "your_sql_table_name",
    "spreadsheet_id" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "target" : "mysql",
    "range" : "A:ZZ"
  } ],
  "targets" : {
    "mysql" : {
      "dbtype" : "mysql",
      "dbname" : "ttt",
      "host" : "localhost",
      "user" : "root",
      "useUnicode": "yes",
      "characterEncoding": "UTF-8"
    },
    "psql" : {
      "dbtype" : "postgresql",
      "dbname" : "testdb",
      "host" : "localhost",
      "password" : "xxxxx",
      "user" : "xxxxx"
    }
  },
  "google_credentials" : {
    "client_id" : "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
    "client_secret" : "xxxxxxxxxxxxxxxxxxxxxxxx",
    "redirect_uri" : "http://localhost:9955/oauth"
  },
  "interval" : {
    "days" : 0,
    "hours" : 0,
    "minutes" : 30,
    "seconds" : 0
  }
}
```

**Comment by c0mpute123** [comment]
Perfect!  Thank you.  That did it.
