### ISSUE TITLE
Upload?

### ISSUE THREAD

**Issue by c0mpute123** [jorinvo/googlesheets-sql-sync#21]
This is great to download sheet content into a table.  Any way to do the reverse and upload a table into a Google Sheet?  I know it says for reading only, but I also know the reverse is possible.  Just wondered if you had already done it.

**Comment by jorinvo** [comment]
Sorry, no. It's not in the scope of this tool here and personally I never had a use for this so I cannot point you to any other resources. Still, I am sure there is some tool out there somewhere to do this :slightly_smiling_face:

**Comment by c0mpute123** [comment]
Nothing that isn't SAS or some other language that does one row/column at a time..  Guess we'll have to write our own.  If it is in alignment with yours, I'll let you know.
