### ISSUE TITLE
SOLVED: Sync fails due to "unrecognized" time zone

### ISSUE THREAD

**Issue by Soitora** [jorinvo/googlesheets-sql-sync#22]
Hey, some days ago my country (Sweden) switched to Daylight Savings Time (CET -> CEST).

Ever since that switch I haven't been able to sync.
The following error occurs:
```bash
...
Creating table
There was a problem with table "wpam_googlesheets" on target "XS-Server": The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
Sync failed

Shutting down
Stopping worker
```

I looked up on Google and it seems that I either need to pass a `serverTimezone` flag along with the sync script which I don't think I really know how to.

Second is changing the server timezone which I don't think would be a good idea for my other systems.

Is this something you can fix or is there something on my end I need to fix?

Thank you!

Sincerely,
Soitora

**Comment by Soitora** [comment]
I solved this by adding `"serverTimezone" : "Europe/Stockholm"` as a database option under my json target! Found this out after seeing in the install guide:
> "You can find more DB options in the JDBC docs for PostgreSQL or MySQL."

How I could miss originally that is beyond me

**Comment by jorinvo** [comment]
Oh sorry, I totally missed out on this issue! Great you found a solution 😊 
Timezones can be a paint 😉
