### ISSUE TITLE
Unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Soitora** [jorinvo/googlesheets-sql-sync#29]
Hey, suddenly after not having used the program for months I am getting this error:
```java
Got code
Handling auth code
Errror handling code: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Refreshing access token
No refresh_token found
```
Any idea on how to fix this?

**Comment by raudabaugh** [comment]
This appears to be fixed in newer versions of the `http-kit` dependency. Give my PR a try and let me know if that works for you.

**Comment by Soitora** [comment]
Hey, it now works with the connection, but I haven't modified my table since I last used the program (and it worked), but I'm getting this error now instead:

```java
Got code
Handling auth code
Refreshing access token
Fetching data for [REDACTED]
nil
Updating table wpam_googlesheets
Getting table headers
Clearing table
Writing 2054 rows to table
There was a problem with table "wpam_googlesheets" on target "FS Data Server": You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"id", "song_uri", "song_title", "song_englishTitle", "song_japaneseTitle", "s...' at line 1
Sync failed
```

Now it cleared my table for my website but failed to generate a new one

**Comment by jorinvo** [comment]
Thanks for the merge request! I made a new release with the http-kit update:

https://github.com/jorinvo/googlesheets-sql-sync/releases/tag/0.7.1

Could you please open a new issue if you are still having the above issue regarding SQL syntax? Thanks :)
