### ISSUE TITLE
Sync from PostgreSQL -> Sheets

### ISSUE THREAD

**Issue by flutter-painter** [jorinvo/googlesheets-sql-sync#4]
Hey @jorinvo,

Sorry for the lack of details on my previous issue. My understanding of **googlesheets-sql-sync** is that spreadsheets sync to the **PostgreSQL** db.
Would it also be possible to sync from the PostgreSQL to the google sheets ?

**Comment by jorinvo** [comment]
Hi, now I got it. But I'm sorry, that's outside of the scope of this project. I'm sure you find some other solution :)
