### ISSUE TITLE
SQL Server -> Sheets

### ISSUE THREAD

**Issue by fgarat-nexa** [jorinvo/googlesheets-sql-sync#5]
Hi, it's possible to implement one way sync from SQL Server to Google Sheets?.

Thanks.

**Comment by jorinvo** [comment]
Sorry, this project is only about syncing from Google Sheets to SQL DBs, not the other way around (also see [this issue](https://github.com/jorinvo/googlesheets-sql-sync/issues/4) about Postgres to Sheets).
