### ISSUE TITLE
Support for MySQL?

### ISSUE THREAD

**Issue by cyn8** [jorinvo/googlesheets-sql-sync#7]
Just wondering if MySQL support could be added, as my organization requires use of MySQL for compatibility with other projects.

**Comment by jorinvo** [comment]
Hi @cyn8! Sure, Adding a new driver is simple.
I prepared a new release with MySQL support: 
https://github.com/jorinvo/googlesheets-sql-sync/releases/tag/0.5.0

In the config file you then need to set `"dbtype": "mysql"`

I'm closing this for now. Feel free to comment/reopen if you have anything!

**Comment by cyn8** [comment]
Hi, thanks for the quick update! I am getting an error after running however.

```
Updating table xxxx
Getting table headers
Table is empty, dropping it
Creating table
There was a problem with table "xxxx" on target "my_target": You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"Status" text, "Order ID " text, "Number" text )' at line 1 
```

Thanks in advance.
