### ISSUE TITLE
Sync once - no interval

### ISSUE THREAD

**Issue by smclay84** [jorinvo/googlesheets-sql-sync#9]
Im looking to run this via a batch file that is set to run via a windows service at specific times but cant find a way to get it to ignore the interval - any advice?

**Comment by jorinvo** [comment]
Hi @muttley616! I added a `--single-sync` flag so you can stop the service after the first sync.
Please try out the release [0.6.0](https://github.com/jorinvo/googlesheets-sql-sync/releases/tag/0.6.0).
Also mentioned the option in the [readme](https://github.com/jorinvo/googlesheets-sql-sync#single-sync) now.

**Comment by jorinvo** [comment]
I'm closing this for now. But feel free to re-open when you have any issues.
